-- UniEco clean staging baseline. Local authoring only; not applied remotely.
-- Source map: schema/security from historical 0001-0021 and 0025-0028,
-- reconciled to Phase A1/A2. Intentionally excludes 0012, 0013, 0015,
-- historical 0022-0024, referrals, wallets, and all demo/business data.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.user_roles (id smallint PRIMARY KEY, name text UNIQUE NOT NULL, description text);
INSERT INTO public.user_roles (id,name,description) VALUES
 (1,'visitor','Unauthenticated browsing user'),(2,'student','Authenticated student'),
 (3,'student_vendor','Verified student business operator'),(4,'external_vendor','Business operator'),
 (5,'moderator','Content moderator'),(6,'super_admin','Platform administrator') ON CONFLICT DO NOTHING;

CREATE TABLE public.universities (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, short_name text UNIQUE NOT NULL,
 slug text UNIQUE NOT NULL, city text, region text, country text NOT NULL DEFAULT 'Ghana', logo_url text,
 website_url text, description text, is_enabled boolean NOT NULL DEFAULT false,
 hero_image_url text, logo_alt_text text, hero_alt_text text, image_credit text, image_source text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.profiles (
 id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id),
 role_id smallint NOT NULL DEFAULT 2 REFERENCES public.user_roles(id), email text NOT NULL, full_name text, phone text,
 avatar_url text, bio text, is_active boolean NOT NULL DEFAULT true, status text NOT NULL DEFAULT 'active',
 preferences jsonb NOT NULL DEFAULT '{}'::jsonb, notification_settings jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.student_profiles (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id),
 student_id_number text, program_of_study text, faculty text, department text, level text, admission_year int,
 graduation_year int, is_verified_student boolean NOT NULL DEFAULT false, verification_status text NOT NULL DEFAULT 'pending',
 student_id_document_url text, rejection_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.vendors (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid REFERENCES public.universities(id),
 owner_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, business_name text NOT NULL, business_slug text UNIQUE NOT NULL,
 business_type text, description text, is_student_business boolean NOT NULL DEFAULT false, is_verified boolean NOT NULL DEFAULT false,
 is_active boolean NOT NULL DEFAULT false, logo_url text, cover_image_url text, contact_phone text, contact_email text, website_url text,
 whatsapp_number text, social_links jsonb NOT NULL DEFAULT '{}'::jsonb, delivery_available boolean NOT NULL DEFAULT false,
 service_radius_km int, gps_latitude numeric(9,6), gps_longitude numeric(9,6), is_temporarily_closed boolean NOT NULL DEFAULT false,
 opening_hours jsonb DEFAULT '{}'::jsonb, rating_avg numeric(3,2) NOT NULL DEFAULT 0, rating_count int NOT NULL DEFAULT 0,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.vendor_profiles (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 vendor_type text NOT NULL DEFAULT 'student_vendor', verification_status text NOT NULL DEFAULT 'pending', subscription_status text NOT NULL DEFAULT 'none',
 business_category text, location_address text, location_city text, location_region text, product_service_type text,
 verification_document_url text, rejection_reason text, approved_at timestamptz, approved_by uuid REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.verification_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, request_type text NOT NULL, documents jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'pending', admin_note text, reviewed_by uuid REFERENCES public.profiles(id), reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES public.profiles(id), target_id uuid, action text NOT NULL, entity_type text, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.role_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role text NOT NULL, permission text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(role,permission));
CREATE TABLE public.index_number_verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid NOT NULL REFERENCES public.universities(id), index_number text NOT NULL, student_profile_id uuid REFERENCES public.student_profiles(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'pending', is_duplicate boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(university_id,index_number));
CREATE TABLE public.university_admin_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, university_id uuid NOT NULL REFERENCES public.universities(id) ON DELETE CASCADE, is_active boolean NOT NULL DEFAULT true, assigned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, assigned_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,university_id));

-- These helpers establish database-backed authorization before A1 replaces
-- them with its audited implementation. They never inspect auth metadata.
CREATE OR REPLACE FUNCTION public.current_app_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT role.name FROM public.profiles profile JOIN public.user_roles role ON role.id=profile.role_id WHERE profile.id=auth.uid() LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.is_super_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT COALESCE(public.current_app_role()='super_admin',false) $$;
CREATE OR REPLACE FUNCTION public.is_staff() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT COALESCE(public.current_app_role() IN ('moderator','super_admin'),false) $$;
CREATE OR REPLACE FUNCTION public.can_manage_university(p_university_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT public.is_super_admin() OR EXISTS(SELECT 1 FROM public.university_admin_memberships membership WHERE membership.user_id=auth.uid() AND membership.university_id=p_university_id AND membership.is_active) $$;
REVOKE ALL ON FUNCTION public.current_app_role() FROM PUBLIC; REVOKE ALL ON FUNCTION public.is_super_admin() FROM PUBLIC; REVOKE ALL ON FUNCTION public.is_staff() FROM PUBLIC; REVOKE ALL ON FUNCTION public.can_manage_university(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_role() TO authenticated; GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated; GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated; GRANT EXECUTE ON FUNCTION public.can_manage_university(uuid) TO authenticated;

CREATE TABLE public.businesses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id), name text NOT NULL, slug text UNIQUE NOT NULL, description text, category text, logo_url text, is_active boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id), name text NOT NULL, slug text UNIQUE NOT NULL, description text, price numeric(12,2) NOT NULL CHECK(price>=0), discount_price numeric(12,2), currency text NOT NULL DEFAULT 'GHS', stock int NOT NULL DEFAULT 0 CHECK(stock>=0), image_url text, images jsonb NOT NULL DEFAULT '[]'::jsonb, sku text, tags text[] DEFAULT '{}', is_active boolean NOT NULL DEFAULT false, is_archived boolean NOT NULL DEFAULT false, low_stock_threshold int NOT NULL DEFAULT 5, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id), name text NOT NULL, slug text UNIQUE NOT NULL, description text, price numeric(12,2) NOT NULL CHECK(price>=0), currency text NOT NULL DEFAULT 'GHS', duration_estimate text, image_url text, images jsonb NOT NULL DEFAULT '[]'::jsonb, is_active boolean NOT NULL DEFAULT false, is_archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.locations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid REFERENCES public.universities(id), owner_type text, owner_id uuid, label text, address_line text, city text, region text, latitude numeric(9,6), longitude numeric(9,6), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, slug text UNIQUE NOT NULL, description text, icon text, parent_id uuid REFERENCES public.categories(id) ON DELETE SET NULL, sort_order int NOT NULL DEFAULT 0, is_visible boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.saved_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE, item_type text NOT NULL CHECK(item_type IN ('business','product','service','event')), item_id uuid NOT NULL, collection text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,item_type,item_id));
CREATE TABLE public.recently_viewed (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE, item_type text NOT NULL CHECK(item_type IN ('business','product','service','event')), item_id uuid NOT NULL, viewed_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,item_type,item_id));
CREATE TABLE public.student_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL DEFAULT auth.uid() UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE, interests text[] NOT NULL DEFAULT '{}', notification_preferences jsonb NOT NULL DEFAULT '{"email":true,"push":true,"events":true,"messages":true,"reviews":true,"announcements":true}'::jsonb, privacy_settings jsonb NOT NULL DEFAULT '{"profile_visibility":"university","contact_visibility":"university"}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.wishlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE, item_type text NOT NULL CHECK(item_type IN ('product','service')), item_id uuid NOT NULL, collection text NOT NULL DEFAULT 'Favorites', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,item_type,item_id));

CREATE TABLE public.orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid REFERENCES public.universities(id), buyer_id uuid NOT NULL REFERENCES public.profiles(id), vendor_id uuid REFERENCES public.vendors(id), status text NOT NULL DEFAULT 'pending', total_amount numeric(12,2) NOT NULL CHECK(total_amount>=0), currency text NOT NULL DEFAULT 'GHS', notes text, order_number text UNIQUE, order_type text NOT NULL DEFAULT 'product' CHECK(order_type IN('product','service','mixed')), delivery_method text DEFAULT 'pickup' CHECK(delivery_method IN('pickup','delivery')), delivery_address jsonb, delivery_fee numeric(12,2) NOT NULL DEFAULT 0, delivery_instructions text, estimated_completion timestamptz, coupon_code text, coupon_discount numeric(12,2) NOT NULL DEFAULT 0, accepted_at timestamptz, completed_at timestamptz, cancelled_at timestamptz, cancellation_reason text, vendor_notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE, product_id uuid REFERENCES public.products(id), service_id uuid REFERENCES public.services(id), quantity int NOT NULL DEFAULT 1 CHECK(quantity>0), unit_price numeric(12,2) NOT NULL CHECK(unit_price>=0), unit_name text, unit_image_url text, item_name text, booking_date date, booking_time time, booking_notes text, booking_status text DEFAULT 'pending', rescheduled_to timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK((product_id IS NOT NULL)::int + (service_id IS NOT NULL)::int = 1));
CREATE TABLE public.carts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE, coupon_code text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.cart_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), cart_id uuid NOT NULL REFERENCES public.carts(id) ON DELETE CASCADE, product_id uuid REFERENCES public.products(id) ON DELETE CASCADE, service_id uuid REFERENCES public.services(id) ON DELETE CASCADE, quantity int NOT NULL DEFAULT 1 CHECK(quantity>0), save_for_later boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), CHECK((product_id IS NOT NULL)::int + (service_id IS NOT NULL)::int = 1));
CREATE TABLE public.coupons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, description text, discount_type text NOT NULL DEFAULT 'percentage' CHECK(discount_type IN('percentage','fixed')), discount_value numeric(12,2) NOT NULL DEFAULT 0 CHECK(discount_value>=0), min_order_amount numeric(12,2) NOT NULL DEFAULT 0, max_discount_amount numeric(12,2), student_only boolean NOT NULL DEFAULT false, vendor_id uuid REFERENCES public.vendors(id) ON DELETE CASCADE, university_id uuid REFERENCES public.universities(id) ON DELETE CASCADE, usage_limit int, usage_count int NOT NULL DEFAULT 0, per_user_limit int NOT NULL DEFAULT 1, starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz NOT NULL DEFAULT(now()+interval '30 days'), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.coupon_redemptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), coupon_id uuid NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL, redeemed_at timestamptz NOT NULL DEFAULT now(), UNIQUE(coupon_id,user_id));
CREATE TABLE public.order_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE, previous_status text, new_status text NOT NULL, changed_by uuid REFERENCES public.profiles(id), note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.order_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE, sender_id uuid NOT NULL REFERENCES public.profiles(id), recipient_id uuid NOT NULL REFERENCES public.profiles(id), body text NOT NULL, is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE, provider text, provider_reference text UNIQUE, amount numeric(12,2) NOT NULL CHECK(amount>=0), currency text NOT NULL DEFAULT 'GHS', status text NOT NULL DEFAULT 'pending', paid_at timestamptz, payment_reference text, user_id uuid REFERENCES public.profiles(id), vendor_id uuid REFERENCES public.vendors(id), payment_type text NOT NULL DEFAULT 'marketplace', entity_id uuid, mobile_number text, mobile_network text, failure_reason text, webhook_received boolean NOT NULL DEFAULT false, webhook_data jsonb NOT NULL DEFAULT '{}'::jsonb, idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, plan text NOT NULL DEFAULT 'free', status text NOT NULL DEFAULT 'pending', started_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, provider_reference text, amount numeric(12,2), currency text NOT NULL DEFAULT 'GHS', payment_method text, payment_reference text, auto_renew boolean NOT NULL DEFAULT false, cancelled_at timestamptz, renewal_failed_at timestamptz, extended_by uuid REFERENCES public.profiles(id), extension_note text, next_billing_date timestamptz, last_payment_id uuid REFERENCES public.payments(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, invoice_number text UNIQUE NOT NULL, invoice_type text NOT NULL DEFAULT 'subscription', reference_id uuid, amount numeric(12,2) NOT NULL CHECK(amount>=0), currency text NOT NULL DEFAULT 'GHS', status text NOT NULL DEFAULT 'pending', payment_reference text, issued_at timestamptz NOT NULL DEFAULT now(), paid_at timestamptz, user_id uuid REFERENCES public.profiles(id), payment_id uuid REFERENCES public.payments(id), entity_id uuid, tax_amount numeric(12,2) NOT NULL DEFAULT 0, total_amount numeric(12,2), due_date timestamptz, notes text, billing_name text, billing_email text, billing_phone text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.invoice_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE, description text NOT NULL, quantity integer NOT NULL CHECK(quantity>0), unit_price numeric(12,2) NOT NULL CHECK(unit_price>=0), total_price numeric(12,2) NOT NULL CHECK(total_price>=0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE, receipt_number text UNIQUE NOT NULL, generated_at timestamptz NOT NULL DEFAULT now(), data jsonb NOT NULL DEFAULT '{}'::jsonb, payment_id uuid REFERENCES public.payments(id), user_id uuid REFERENCES public.profiles(id), vendor_id uuid REFERENCES public.vendors(id), receipt_type text NOT NULL DEFAULT 'marketplace', amount numeric(12,2), currency text NOT NULL DEFAULT 'GHS', payment_method text, billing_name text, billing_email text);
CREATE TABLE public.payment_providers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, display_name text NOT NULL, is_enabled boolean NOT NULL DEFAULT false, supported_methods text[] NOT NULL DEFAULT '{}', config jsonb NOT NULL DEFAULT '{}'::jsonb, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO public.payment_providers(name,display_name,is_enabled,supported_methods,sort_order) VALUES ('hubtel','Hubtel Mobile Money',false,ARRAY['mtn_momo','vodafone_cash','airteltigo_money','visa','mastercard'],1),('paystack','Paystack',false,ARRAY['mtn_momo','vodafone_cash','airteltigo_money','visa','mastercard'],2),('flutterwave','Flutterwave',false,ARRAY['mtn_momo','vodafone_cash','airteltigo_money','visa','mastercard'],3),('manual','Manual / Bank Transfer',true,ARRAY['bank_transfer'],99) ON CONFLICT DO NOTHING;

CREATE TABLE public.conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), participant_one uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, participant_two uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL, is_archived boolean NOT NULL DEFAULT false, archived_at timestamptz, last_message_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(participant_one,participant_two), CHECK(participant_one<>participant_two));
CREATE TABLE public.messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, recipient_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, conversation_id uuid REFERENCES public.conversations(id) ON DELETE SET NULL, order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL, body text, message_type text NOT NULL DEFAULT 'text', attachment_url text, is_read boolean NOT NULL DEFAULT false, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, is_archived_by_sender boolean NOT NULL DEFAULT false, is_archived_by_recipient boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, type text, title text, body text, link text, category text NOT NULL DEFAULT 'general', action_url text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, icon text, is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.notification_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, preferences jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.communication_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_key text UNIQUE NOT NULL, name text NOT NULL, channel text NOT NULL, subject text, body text NOT NULL, variables text[] NOT NULL DEFAULT '{}', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reporter_id uuid NOT NULL REFERENCES public.profiles(id), target_type text, target_id uuid, reason text, status text NOT NULL DEFAULT 'open', moderator_id uuid REFERENCES public.profiles(id), resolution_note text, priority text NOT NULL DEFAULT 'medium', report_reason_category text, created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
CREATE TABLE public.events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid REFERENCES public.universities(id), organizer_id uuid NOT NULL REFERENCES public.profiles(id), title text NOT NULL, slug text UNIQUE NOT NULL, description text, start_time timestamptz, end_time timestamptz, location text, is_virtual boolean NOT NULL DEFAULT false, cover_image_url text, is_published boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reviewer_id uuid NOT NULL REFERENCES public.profiles(id), vendor_id uuid REFERENCES public.vendors(id), product_id uuid REFERENCES public.products(id), event_id uuid REFERENCES public.events(id), rating int NOT NULL CHECK(rating BETWEEN 1 AND 5), comment text, is_approved boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.support_tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_number text UNIQUE, user_id uuid NOT NULL REFERENCES public.profiles(id), subject text NOT NULL, description text, category text NOT NULL DEFAULT 'general', status text NOT NULL DEFAULT 'open', priority text NOT NULL DEFAULT 'medium', assigned_to uuid REFERENCES public.profiles(id), internal_notes text, closed_at timestamptz, closed_by uuid REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.cms_pages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, title text NOT NULL, content text, page_type text NOT NULL DEFAULT 'blog', is_published boolean NOT NULL DEFAULT false, published_at timestamptz, author_id uuid REFERENCES public.profiles(id), meta_description text, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.cms_faq_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), question text NOT NULL, answer text NOT NULL, category text, sort_order int NOT NULL DEFAULT 0, is_published boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

-- Search and trust/safety foundations used by current public/admin clients.
CREATE TABLE public.search_queries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), query_text text NOT NULL, normalized_query text NOT NULL, result_type text, result_count int NOT NULL DEFAULT 0, university_id uuid REFERENCES public.universities(id), filters jsonb DEFAULT '{}'::jsonb, session_id text, device_type text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.search_clicks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), search_query_id uuid REFERENCES public.search_queries(id) ON DELETE SET NULL, result_type text NOT NULL, result_id uuid, position int, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.search_synonyms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), keyword text UNIQUE NOT NULL, synonyms text[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.search_ranking_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_name text UNIQUE NOT NULL, rule_type text NOT NULL, weight numeric NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, config jsonb DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.report_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, label text NOT NULL, description text, sort_order int NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.trust_badges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, label text NOT NULL, description text, icon_name text, badge_type text, eligibility_criteria jsonb DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.appeals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), appellant_id uuid NOT NULL REFERENCES public.profiles(id), subject_type text NOT NULL, subject_id uuid NOT NULL, reason text NOT NULL, status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.account_restrictions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id), restriction_type text NOT NULL, reason text, is_active boolean NOT NULL DEFAULT true, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.safety_resources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, title text NOT NULL, content text NOT NULL, resource_type text NOT NULL, category text NOT NULL DEFAULT 'general', university_id uuid REFERENCES public.universities(id), is_published boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

-- Active vendor operations. All business content remains owned by the vendor;
-- only public presentation records can be read by unauthenticated visitors.
CREATE TABLE public.business_gallery (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, image_url text NOT NULL, caption text, image_type text NOT NULL DEFAULT 'general' CHECK(image_type IN ('storefront','banner','product_highlight','general')), sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.business_hours (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, day_of_week int NOT NULL CHECK(day_of_week BETWEEN 0 AND 6), is_open boolean NOT NULL DEFAULT false, open_time time, close_time time, UNIQUE(vendor_id,day_of_week));
CREATE TABLE public.business_holidays (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, holiday_date date NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(vendor_id,holiday_date));
CREATE TABLE public.vendor_analytics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL UNIQUE REFERENCES public.vendors(id) ON DELETE CASCADE, profile_views int NOT NULL DEFAULT 0, product_views int NOT NULL DEFAULT 0, service_views int NOT NULL DEFAULT 0, search_appearances int NOT NULL DEFAULT 0, messages_received int NOT NULL DEFAULT 0, saved_count int NOT NULL DEFAULT 0, monthly_profile_views jsonb NOT NULL DEFAULT '{}'::jsonb, monthly_messages jsonb NOT NULL DEFAULT '{}'::jsonb, monthly_reviews jsonb NOT NULL DEFAULT '{}'::jsonb, response_rate numeric NOT NULL DEFAULT 0, avg_response_time_hours numeric NOT NULL DEFAULT 0, trust_score numeric NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.vendor_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL UNIQUE REFERENCES public.vendors(id) ON DELETE CASCADE, email_notifications boolean NOT NULL DEFAULT true, push_notifications boolean NOT NULL DEFAULT true, order_alerts boolean NOT NULL DEFAULT true, review_alerts boolean NOT NULL DEFAULT true, message_alerts boolean NOT NULL DEFAULT true, two_factor_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.review_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), review_id uuid NOT NULL UNIQUE REFERENCES public.reviews(id) ON DELETE CASCADE, vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, response_body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

-- Advertising remains a moderated, empty structural capability: neither a
-- request nor a listing becomes sponsored/active without staff approval.
CREATE TABLE public.ad_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, ad_type text NOT NULL CHECK(ad_type IN ('featured_business','homepage_banner','category_promotion','search_promotion','event_promotion')), title text NOT NULL, description text, image_url text, target_url text, requested_duration_days int NOT NULL CHECK(requested_duration_days>0), estimated_reach text, estimated_cost numeric(12,2) NOT NULL CHECK(estimated_cost>=0), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','active','completed')), admin_note text, reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, reviewed_at timestamptz, starts_at timestamptz, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.advertisements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid REFERENCES public.vendors(id) ON DELETE SET NULL, university_id uuid REFERENCES public.universities(id) ON DELETE SET NULL, title text, image_url text, target_url text, placement text, starts_at timestamptz, ends_at timestamptz, is_active boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','active','completed','paused')), reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, reviewed_at timestamptz, rejection_reason text, priority int NOT NULL DEFAULT 0, is_featured boolean NOT NULL DEFAULT false, is_sponsored boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.featured_listings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), listing_type text NOT NULL CHECK(listing_type IN ('business','product','service','event')), listing_id uuid NOT NULL, placement_type text NOT NULL CHECK(placement_type IN ('sponsored','featured','boosted')), search_keyword text, university_id uuid REFERENCES public.universities(id) ON DELETE CASCADE, priority int NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT false, start_date timestamptz, end_date timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

-- Current communication clients write only user-owned preference, blocking,
-- receipt and announcement records. Provider queues/logs are server-only.
CREATE TABLE public.message_reads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), message_id uuid NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, read_at timestamptz NOT NULL DEFAULT now(), UNIQUE(message_id,user_id));
CREATE TABLE public.communication_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_type text NOT NULL, recipient_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, recipient_email text, recipient_phone text, subject text, channels text[] NOT NULL DEFAULT ARRAY['in_app'], status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','sent','delivered','failed','cancelled')), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.communication_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_id uuid NOT NULL REFERENCES public.communication_events(id) ON DELETE CASCADE, channel text NOT NULL CHECK(channel IN ('in_app','email','push','whatsapp','sms')), status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sent','delivered','failed','opened','read')), provider text, provider_reference text, error_message text, sent_at timestamptz, delivered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.communication_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_type text NOT NULL, channel text NOT NULL, recipient_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, recipient_identifier text, status text NOT NULL, provider text, provider_reference text, university_id uuid REFERENCES public.universities(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.push_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, endpoint text NOT NULL, p256dh_key text NOT NULL, auth_key text NOT NULL, expiration_time timestamptz, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,endpoint));
CREATE TABLE public.blocked_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), blocker_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, blocked_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, reason text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(blocker_id,blocked_id), CHECK(blocker_id<>blocked_id));
CREATE TABLE public.message_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reporter_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, reported_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, message_id uuid REFERENCES public.messages(id) ON DELETE SET NULL, conversation_id uuid REFERENCES public.conversations(id) ON DELETE SET NULL, reason text NOT NULL, description text, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','reviewing','resolved','dismissed')), reviewed_by uuid REFERENCES public.profiles(id), reviewed_at timestamptz, resolution_note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.business_announcements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, title text NOT NULL, body text NOT NULL, announcement_type text NOT NULL DEFAULT 'general' CHECK(announcement_type IN ('new_product','holiday_hours','temporary_closure','special_promotion','general')), image_url text, is_active boolean NOT NULL DEFAULT true, is_approved boolean NOT NULL DEFAULT false, reviewed_by uuid REFERENCES public.profiles(id), reviewed_at timestamptz, starts_at timestamptz, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.admin_broadcasts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, body text NOT NULL, broadcast_type text NOT NULL DEFAULT 'announcement' CHECK(broadcast_type IN ('announcement','maintenance','update','event','promotion')), target_audience text NOT NULL DEFAULT 'all' CHECK(target_audience IN ('all','students','vendors','specific_university','specific_category','selected_users')), target_filters jsonb NOT NULL DEFAULT '{}'::jsonb, channels text[] NOT NULL DEFAULT ARRAY['in_app'], status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','scheduled','pending_approval','approved','sending','sent','cancelled')), scheduled_at timestamptz, sent_at timestamptz, sent_count int NOT NULL DEFAULT 0, failed_count int NOT NULL DEFAULT 0, created_by uuid NOT NULL REFERENCES public.profiles(id), approved_by uuid REFERENCES public.profiles(id), approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.university_announcements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), university_id uuid NOT NULL REFERENCES public.universities(id) ON DELETE CASCADE, title text NOT NULL, body text NOT NULL, announcement_type text NOT NULL DEFAULT 'general', is_active boolean NOT NULL DEFAULT true, is_pinned boolean NOT NULL DEFAULT false, created_by uuid NOT NULL REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.event_reminders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, event_id uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, reminder_type text NOT NULL DEFAULT '24h' CHECK(reminder_type IN ('24h','1h','custom')), custom_minutes_before int, is_sent boolean NOT NULL DEFAULT false, sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,event_id,reminder_type));

-- Admin support and audit records are staff-only except for a ticket owner's
-- own non-internal replies. These tables have no public browser-write path.
CREATE TABLE public.ticket_replies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, body text NOT NULL, is_internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.announcements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, body text NOT NULL, type text NOT NULL DEFAULT 'platform' CHECK(type IN ('platform','university','maintenance','promotional')), target_audience text NOT NULL DEFAULT 'all' CHECK(target_audience IN ('all','students','vendors','specific_university')), university_id uuid REFERENCES public.universities(id) ON DELETE CASCADE, is_active boolean NOT NULL DEFAULT true, starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz NOT NULL DEFAULT(now()+interval '7 days'), created_by uuid NOT NULL REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.admin_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), admin_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, action text NOT NULL, module text NOT NULL, target_type text, target_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, ip_address inet, result text NOT NULL DEFAULT 'success' CHECK(result IN ('success','failure')), created_at timestamptz NOT NULL DEFAULT now());

-- Search/discovery and trust records are data-free configuration/operational
-- structures. Sensitive moderation and risk records have no public policy.
CREATE TABLE public.content_quality_flags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), content_type text NOT NULL CHECK(content_type IN ('business','product','service','event','review','announcement')), content_id uuid NOT NULL, flag_reason text NOT NULL, flag_details text, flagged_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, is_auto_detected boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','reviewing','resolved','dismissed')), resolved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.moderation_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_number text NOT NULL UNIQUE DEFAULT ('MC-'||upper(substr(encode(gen_random_bytes(6),'hex'),1,8))), case_type text NOT NULL, severity text NOT NULL DEFAULT 'medium' CHECK(severity IN ('low','medium','high','critical')), status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','investigating','waiting_info','resolved','dismissed','escalated')), title text NOT NULL, description text, reporter_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, subject_type text NOT NULL, subject_id text NOT NULL, university_id uuid REFERENCES public.universities(id) ON DELETE SET NULL, assigned_to uuid REFERENCES public.profiles(id) ON DELETE SET NULL, priority int NOT NULL DEFAULT 0, resolution text, resolved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.moderation_case_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.moderation_cases(id) ON DELETE CASCADE, linked_type text NOT NULL, linked_id text NOT NULL, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.moderation_case_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.moderation_cases(id) ON DELETE CASCADE, event_type text NOT NULL, actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.user_trust_badges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), badge_id uuid NOT NULL REFERENCES public.trust_badges(id) ON DELETE CASCADE, user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE, vendor_id uuid REFERENCES public.vendors(id) ON DELETE CASCADE, awarded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, awarded_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, is_active boolean NOT NULL DEFAULT true, revoked_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, revoked_at timestamptz, revocation_reason text, created_at timestamptz NOT NULL DEFAULT now(), CHECK(user_id IS NOT NULL OR vendor_id IS NOT NULL));
CREATE TABLE public.risk_signals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL CHECK(subject_type IN ('user','vendor','business')), subject_id uuid NOT NULL, signal_type text NOT NULL, signal_weight numeric NOT NULL DEFAULT 1 CHECK(signal_weight BETWEEN 0 AND 10), description text, source text NOT NULL DEFAULT 'auto' CHECK(source IN ('auto','manual')), is_active boolean NOT NULL DEFAULT true, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.risk_score_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL CHECK(subject_type IN ('user','vendor','business')), subject_id uuid NOT NULL, score int NOT NULL CHECK(score BETWEEN 0 AND 100), calculated_at timestamptz NOT NULL DEFAULT now(), factors jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE public.verification_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, entity_id uuid NOT NULL, previous_status text, new_status text NOT NULL, changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, reason text, notes text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.document_access_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_url text NOT NULL, document_type text NOT NULL, accessed_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL, owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, access_reason text, verification_request_id uuid REFERENCES public.verification_requests(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.review_moderation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), review_id uuid NOT NULL UNIQUE REFERENCES public.reviews(id) ON DELETE CASCADE, moderation_status text NOT NULL DEFAULT 'published' CHECK(moderation_status IN ('published','pending_review','flagged','hidden','removed')), flag_reason text, flagged_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, flagged_at timestamptz, moderated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, moderated_at timestamptz, moderation_note text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.category_safety_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), category text NOT NULL UNIQUE, requires_verification boolean NOT NULL DEFAULT false, required_verification_level text NOT NULL DEFAULT 'basic', documentation_required text[] NOT NULL DEFAULT '{}', advertising_restricted boolean NOT NULL DEFAULT false, review_required_before_publish boolean NOT NULL DEFAULT false, additional_notes text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.business_duplicate_flags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id_1 uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, business_id_2 uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE, match_signals jsonb NOT NULL DEFAULT '{}'::jsonb, confidence_score numeric(3,2) NOT NULL DEFAULT .5 CHECK(confidence_score BETWEEN 0 AND 1), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','reviewing','resolved','dismissed')), resolved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, resolution text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(business_id_1<>business_id_2));

-- Least-privilege baseline: RLS is enabled everywhere; Phase A1 replaces legacy role policy assumptions.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['user_roles','universities','profiles','student_profiles','vendors','vendor_profiles','verification_requests','audit_logs','role_permissions','index_number_verifications','businesses','products','services','locations','categories','saved_items','recently_viewed','student_preferences','wishlists','orders','order_items','carts','cart_items','coupons','coupon_redemptions','order_status_history','order_messages','payments','subscriptions','invoices','invoice_items','receipts','payment_providers','conversations','messages','notifications','notification_preferences','communication_templates','reports','events','reviews','support_tickets','cms_pages','cms_faq_entries','search_queries','search_clicks','search_synonyms','search_ranking_rules','report_categories','trust_badges','appeals','account_restrictions','safety_resources'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); END LOOP; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['university_admin_memberships','business_gallery','business_hours','business_holidays','vendor_analytics','vendor_settings','review_responses','ad_requests','advertisements','featured_listings','message_reads','communication_events','communication_deliveries','communication_logs','push_subscriptions','blocked_users','message_reports','business_announcements','admin_broadcasts','university_announcements','event_reminders','ticket_replies','announcements','admin_actions','content_quality_flags','moderation_cases','moderation_case_links','moderation_case_events','user_trust_badges','risk_signals','risk_score_history','verification_history','document_access_logs','review_moderation','category_safety_policies','business_duplicate_flags'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); END LOOP; END $$;
CREATE POLICY profiles_self_read ON public.profiles FOR SELECT TO authenticated USING(auth.uid()=id);
CREATE POLICY carts_owner ON public.carts FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE POLICY cart_items_owner ON public.cart_items FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.carts c WHERE c.id=cart_id AND c.user_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.carts c WHERE c.id=cart_id AND c.user_id=auth.uid()));
CREATE POLICY conversations_participant ON public.conversations FOR SELECT TO authenticated USING(auth.uid() IN(participant_one,participant_two));
CREATE POLICY messages_participant ON public.messages FOR SELECT TO authenticated USING(auth.uid() IN(sender_id,recipient_id));
CREATE POLICY notifications_owner ON public.notifications FOR SELECT TO authenticated USING(auth.uid()=user_id);
CREATE POLICY public_enabled_universities ON public.universities FOR SELECT TO anon,authenticated USING(is_enabled);
CREATE POLICY public_categories ON public.categories FOR SELECT TO anon,authenticated USING(is_visible);
CREATE POLICY public_products ON public.products FOR SELECT TO anon,authenticated USING(is_active AND NOT is_archived);
CREATE POLICY public_services ON public.services FOR SELECT TO anon,authenticated USING(is_active AND NOT is_archived);
CREATE POLICY public_vendors ON public.vendors FOR SELECT TO anon,authenticated USING(is_active);
CREATE POLICY public_businesses ON public.businesses FOR SELECT TO anon,authenticated USING(is_active);
CREATE POLICY saved_items_owner ON public.saved_items FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY recently_viewed_owner ON public.recently_viewed FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY student_preferences_owner ON public.student_preferences FOR ALL TO authenticated USING(student_id=auth.uid()) WITH CHECK(student_id=auth.uid());
CREATE POLICY wishlists_owner ON public.wishlists FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY reviews_public_approved ON public.reviews FOR SELECT TO anon,authenticated USING(is_approved OR reviewer_id=auth.uid() OR public.is_staff());
CREATE POLICY reviews_owner_manage ON public.reviews FOR ALL TO authenticated USING(reviewer_id=auth.uid()) WITH CHECK(reviewer_id=auth.uid() AND is_approved=false);
CREATE POLICY events_public_published ON public.events FOR SELECT TO anon,authenticated USING(is_published);
CREATE POLICY events_owner_manage ON public.events FOR ALL TO authenticated USING(organizer_id=auth.uid()) WITH CHECK(organizer_id=auth.uid() AND is_published=false);
CREATE POLICY reports_owner_insert ON public.reports FOR INSERT TO authenticated WITH CHECK(reporter_id=auth.uid());
CREATE POLICY reports_owner_read ON public.reports FOR SELECT TO authenticated USING(reporter_id=auth.uid() OR public.is_staff());
CREATE POLICY reports_staff_update ON public.reports FOR UPDATE TO authenticated USING(public.is_staff()) WITH CHECK(public.is_staff());
CREATE POLICY tickets_owner_manage ON public.support_tickets FOR ALL TO authenticated USING(user_id=auth.uid() OR public.is_staff()) WITH CHECK(user_id=auth.uid() OR public.is_staff());
CREATE POLICY gallery_public_read ON public.business_gallery FOR SELECT TO anon,authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.is_active));
CREATE POLICY gallery_vendor_manage ON public.business_gallery FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY hours_public_read ON public.business_hours FOR SELECT TO anon,authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.is_active));
CREATE POLICY hours_vendor_manage ON public.business_hours FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY holidays_vendor_manage ON public.business_holidays FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY analytics_vendor_read ON public.vendor_analytics FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY settings_vendor_manage ON public.vendor_settings FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY responses_vendor_manage ON public.review_responses FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid()));
CREATE POLICY ad_requests_vendor_manage ON public.ad_requests FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid() AND status='pending'));
CREATE POLICY advertisements_staff_read ON public.advertisements FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY advertisements_staff_manage ON public.advertisements FOR ALL TO authenticated USING(public.is_staff()) WITH CHECK(public.is_staff());
CREATE POLICY featured_listings_public_read ON public.featured_listings FOR SELECT TO anon,authenticated USING(is_active AND (start_date IS NULL OR start_date<=now()) AND (end_date IS NULL OR end_date>=now()));
CREATE POLICY message_reads_own ON public.message_reads FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY push_subscriptions_own ON public.push_subscriptions FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY blocks_own ON public.blocked_users FOR ALL TO authenticated USING(blocker_id=auth.uid()) WITH CHECK(blocker_id=auth.uid());
CREATE POLICY message_reports_own_insert ON public.message_reports FOR INSERT TO authenticated WITH CHECK(reporter_id=auth.uid());
CREATE POLICY message_reports_own_read ON public.message_reports FOR SELECT TO authenticated USING(reporter_id=auth.uid() OR public.is_staff());
CREATE POLICY business_announcements_vendor_manage ON public.business_announcements FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.vendors v WHERE v.id=vendor_id AND v.owner_id=auth.uid() AND is_approved=false));
CREATE POLICY business_announcements_public_read ON public.business_announcements FOR SELECT TO anon,authenticated USING(is_active AND is_approved AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now()));
CREATE POLICY admin_broadcasts_staff_manage ON public.admin_broadcasts FOR ALL TO authenticated USING(public.is_staff()) WITH CHECK(public.is_staff() AND created_by=auth.uid());
CREATE POLICY university_announcements_public_read ON public.university_announcements FOR SELECT TO anon,authenticated USING(is_active);
CREATE POLICY university_announcements_scoped_manage ON public.university_announcements FOR ALL TO authenticated USING(public.can_manage_university(university_id)) WITH CHECK(public.can_manage_university(university_id));
CREATE POLICY event_reminders_own ON public.event_reminders FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE POLICY ticket_replies_owner_read ON public.ticket_replies FOR SELECT TO authenticated USING((NOT is_internal AND EXISTS(SELECT 1 FROM public.support_tickets t WHERE t.id=ticket_id AND t.user_id=auth.uid())) OR public.is_staff());
CREATE POLICY ticket_replies_owner_insert ON public.ticket_replies FOR INSERT TO authenticated WITH CHECK(author_id=auth.uid() AND NOT is_internal AND EXISTS(SELECT 1 FROM public.support_tickets t WHERE t.id=ticket_id AND t.user_id=auth.uid()));
CREATE POLICY ticket_replies_staff_insert ON public.ticket_replies FOR INSERT TO authenticated WITH CHECK(public.is_staff() AND author_id=auth.uid());
CREATE POLICY announcements_public_read ON public.announcements FOR SELECT TO anon,authenticated USING(is_active AND starts_at<=now() AND ends_at>=now());
CREATE POLICY announcements_staff_manage ON public.announcements FOR ALL TO authenticated USING(public.is_staff()) WITH CHECK(public.is_staff() AND created_by=auth.uid());
CREATE POLICY staff_only_operational_records ON public.communication_events FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_delivery_records ON public.communication_deliveries FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_communication_logs ON public.communication_logs FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_admin_actions ON public.admin_actions FOR SELECT TO authenticated USING(public.is_super_admin());
CREATE POLICY staff_only_moderation_cases ON public.moderation_cases FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_moderation_links ON public.moderation_case_links FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_moderation_events ON public.moderation_case_events FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_risk_signals ON public.risk_signals FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_risk_score_history ON public.risk_score_history FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_verification_history ON public.verification_history FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_document_access_logs ON public.document_access_logs FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY staff_only_review_moderation ON public.review_moderation FOR SELECT TO authenticated USING(public.is_staff());
CREATE POLICY public_safety_policies ON public.category_safety_policies FOR SELECT TO anon,authenticated USING(is_active);
CREATE POLICY public_trust_badges ON public.user_trust_badges FOR SELECT TO anon,authenticated USING(is_active AND (expires_at IS NULL OR expires_at>now()));

-- The auth trigger is required before A1 replaces its function body. Privileged
-- role assignment cannot originate from user-controlled sign-up metadata.
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$ BEGIN INSERT INTO public.profiles(id,email,role_id,full_name,avatar_url) VALUES(NEW.id,NEW.email,2,NEW.raw_user_meta_data->>'full_name',NEW.raw_user_meta_data->>'avatar_url'); RETURN NEW; END $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE INDEX profiles_role_idx ON public.profiles(role_id); CREATE INDEX profiles_university_idx ON public.profiles(university_id);
CREATE INDEX vendors_owner_idx ON public.vendors(owner_id); CREATE INDEX vendors_university_idx ON public.vendors(university_id);
CREATE INDEX products_business_idx ON public.products(business_id); CREATE INDEX services_business_idx ON public.services(business_id);
CREATE INDEX saved_items_user_created_idx ON public.saved_items(user_id,created_at DESC); CREATE INDEX recently_viewed_user_viewed_idx ON public.recently_viewed(user_id,viewed_at DESC); CREATE INDEX wishlists_user_created_idx ON public.wishlists(user_id,created_at DESC);
CREATE INDEX orders_buyer_idx ON public.orders(buyer_id); CREATE INDEX orders_vendor_idx ON public.orders(vendor_id);
CREATE INDEX order_items_order_idx ON public.order_items(order_id); CREATE INDEX invoices_vendor_idx ON public.invoices(vendor_id);
CREATE INDEX invoice_items_invoice_idx ON public.invoice_items(invoice_id); CREATE INDEX payments_user_idx ON public.payments(user_id);
CREATE INDEX messages_conversation_idx ON public.messages(conversation_id); CREATE INDEX conversations_p1_idx ON public.conversations(participant_one); CREATE INDEX conversations_p2_idx ON public.conversations(participant_two);
CREATE INDEX business_gallery_vendor_sort_idx ON public.business_gallery(vendor_id,sort_order); CREATE INDEX business_hours_vendor_idx ON public.business_hours(vendor_id); CREATE INDEX business_holidays_vendor_date_idx ON public.business_holidays(vendor_id,holiday_date); CREATE INDEX ad_requests_vendor_status_idx ON public.ad_requests(vendor_id,status); CREATE INDEX advertisements_status_dates_idx ON public.advertisements(status,starts_at,ends_at); CREATE INDEX featured_listings_active_idx ON public.featured_listings(listing_type,listing_id) WHERE is_active;
CREATE INDEX communication_events_recipient_status_idx ON public.communication_events(recipient_id,status,created_at DESC); CREATE INDEX communication_deliveries_event_idx ON public.communication_deliveries(event_id); CREATE INDEX communication_logs_created_idx ON public.communication_logs(created_at DESC); CREATE INDEX message_reads_message_user_idx ON public.message_reads(message_id,user_id); CREATE INDEX push_subscriptions_active_idx ON public.push_subscriptions(user_id) WHERE is_active; CREATE INDEX message_reports_status_idx ON public.message_reports(status,created_at DESC); CREATE INDEX ticket_replies_ticket_idx ON public.ticket_replies(ticket_id,created_at); CREATE INDEX admin_actions_created_idx ON public.admin_actions(created_at DESC);
CREATE INDEX moderation_cases_status_priority_idx ON public.moderation_cases(status,severity,created_at DESC); CREATE INDEX moderation_case_links_case_idx ON public.moderation_case_links(case_id); CREATE INDEX moderation_case_events_case_idx ON public.moderation_case_events(case_id,created_at); CREATE INDEX risk_signals_subject_idx ON public.risk_signals(subject_type,subject_id,created_at DESC); CREATE INDEX risk_score_history_subject_idx ON public.risk_score_history(subject_type,subject_id,calculated_at DESC); CREATE INDEX verification_history_entity_idx ON public.verification_history(entity_type,entity_id,created_at DESC); CREATE INDEX review_moderation_status_idx ON public.review_moderation(moderation_status);

INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES
 ('avatars','avatars',true,5242880,ARRAY['image/jpeg','image/png','image/webp','image/gif']),
 ('student-documents','student-documents',false,10485760,ARRAY['image/jpeg','image/png','image/webp','application/pdf']),
 ('vendor-documents','vendor-documents',false,10485760,ARRAY['image/jpeg','image/png','image/webp','application/pdf']),
 ('university-branding','university-branding',true,5242880,ARRAY['image/jpeg','image/png','image/webp']) ON CONFLICT(id) DO NOTHING;
CREATE POLICY avatar_upload_own_folder ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='avatars' AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY student_document_owner ON storage.objects FOR ALL TO authenticated USING(bucket_id='student-documents' AND (storage.foldername(name))[1]=auth.uid()::text) WITH CHECK(bucket_id='student-documents' AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY vendor_document_owner ON storage.objects FOR ALL TO authenticated USING(bucket_id='vendor-documents' AND (storage.foldername(name))[1]=auth.uid()::text) WITH CHECK(bucket_id='vendor-documents' AND (storage.foldername(name))[1]=auth.uid()::text);
COMMIT;
