export const CATEGORY_ICONS: Record<string, string> = {
  'Food & Drinks': '🍽️',
  'Printing & Photocopy': '🖨️',
  Fashion: '👕',
  'Hair & Beauty': '💇',
  'Phone Accessories': '📱',
  Electronics: '🔌',
  Repairs: '🔧',
  Laundry: '🧺',
  Transportation: '🛵',
  Accommodation: '🏠',
  Tutoring: '📚',
  Photography: '📸',
  'Technology Services': '💻',
  'Student Freelancers': '🎓',
  'Other Services': '✨',
};

export const ALL_CATEGORIES = [
  'Food & Drinks',
  'Printing & Photocopy',
  'Fashion',
  'Hair & Beauty',
  'Phone Accessories',
  'Electronics',
  'Repairs',
  'Laundry',
  'Transportation',
  'Accommodation',
  'Tutoring',
  'Photography',
  'Technology Services',
  'Student Freelancers',
  'Other Services',
];

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Food & Drinks': ['food', 'restaurant', 'chop bar', 'waakye', 'jollof', 'kelewele', 'snack', 'drink', 'smoothie', 'juice', 'vendor', 'cafeteria'],
  'Printing & Photocopy': ['printing', 'photocopy', 'print', 'binding', 'lamination', 'stationery', 'document'],
  Fashion: ['fashion', 'clothes', 'shirt', 'trouser', 'tailor', 'sewing', 'apparel', 'boutique'],
  'Hair & Beauty': ['beauty', 'hair', 'braiding', 'manicure', 'pedicure', 'salon', 'barber', 'facial', 'makeup'],
  'Phone Accessories': ['phone', 'accessory', 'case', 'screen protector', 'charger', 'cable', 'gadget'],
  Electronics: ['electronics', 'laptop', 'computer', 'gadget', 'device'],
  Repairs: ['repair', 'fix', 'laptop repair', 'phone repair', 'screen', 'battery', 'diagnosis'],
  Laundry: ['laundry', 'wash', 'dry clean', 'ironing'],
  Transportation: ['transport', 'ride', 'motorbike', 'shuttle', 'taxi', 'okada'],
  Accommodation: ['accommodation', 'hostel', 'room', 'rent', 'housing', 'hall'],
  Tutoring: ['tutoring', 'tutorial', 'books', 'textbook', 'past questions', 'education', 'academic'],
  Photography: ['photography', 'photo', 'camera', 'shoot', 'graduation', 'passport'],
  'Technology Services': ['technology', 'tech', 'software', 'web', 'design', 'coding', 'it'],
  'Student Freelancers': ['freelancer', 'freelance', 'student service', 'gig', 'errand'],
  'Other Services': ['other', 'service', 'general'],
};
